version: '3.3'

services:

    # COMPOSER
    composer:
        container_name: composer
        depends_on: web
        image: composer:1.9
        command: ['composer', 'install']
        restart: 'no'
        working_dir: /var/www/html
        volumes: ./:/var/www/html

    # NPM
    npm: 
        container_name: npm
        depends_on: composer
        image: node:14
        restart: 'no'
        working_dir: /var/www/html
        volumes: ./:/var/www/html
        command: ['npm', 'install']
        ports: 3000:80
        depends_on: web
        networks: 
            fullstack:
                aliases: npm

    # PHP
    phpmyadmin: 
        container_name: phpmyadmin
        depends_on: db
        image: phpmyadmin/phpmyadmin
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITARY: 1
        ports: 8080:80
        network: 
            fullstack:
                aliases: phpmyadmin 

    # WEB
    web:
        container_name: php73
        depends_on: db
        build:
            context: ./    
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes: ./:/var/www/html/
        ports: 8000:80
        network: 
            fullstack:
                aliases: web        

    # DATABASE
    db: 
        container_name: mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports: 6033:3306
        network: 
            fullstack:
                aliases: db   
                
# NETWORKS: 
networks:
    fullstack: 
        name: lampp                
