
version: '3.3'
services: 

# COMPOSER 
composer:
        container_name: app_package_manager
        image: composer:1.9
        command: ['composer', 'install']
        restart: 'no'
        volumes: 
                - ./app


        # PROJECT
        web:
                build:
                        context: ./php        
                        dockerfile: Dockerfile
                container_name: php73
                volumes:
                        - ./php:/var/www/html/
                ports:
                        - 8000:80
                depends_on:
                        - db
                network: 
                        backend:
                                aliases:
                                        - web
        # DATABASE
        db: 
                container_name: mysql8
                image: mysql:8.0
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                environment: 
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: test_db
                        MYSQL_USER: devuser
                        MYSQL_PASSWORD: devpass
                ports: 
                        - 6033:3306
                network: 
                        backend:
                                aliases:
                                        - db
        # PHP MY ADMIN
        phpmyadmin:
                depends_on: 
                        - db
                container_name: phpmyadmin
                image: phpmyadmin/phpmyadmin
                restart: always
                environment: 
                        MYSQL_ROOT_PASSWORD: root
                        PMA_HOST: db
                        PMA_PORT: 3306
                        PMA_ARBITARY: 1
                ports: 
                        - 8080:80
                network: 
                        backend:
                                aliases:
                                        - phpmyadmin



#networks: 
    backend: 
        name: lampp
